export default ConstraintsTypes = {
    BE_NEXT_TO: "BE_NEXT_TO", // P - N
    SEAT_AT_SAME_TABLE: "SEAT_AT_SAME_TABLE", // P - N
    SEAT_AT_SPECIFIC_TABLE: "SEAT_AT_SPECIFIC_TABLE", // P -
    HAVE_EXCLUSIVE_TABLE: "HAVE_EXCLUSIVE_TABLE", // P -
    HAVE_GROUP_EXCLUSIVE_TABLE: "HAVE_GROUP_EXCLUSIVE_TABLE"
}